{{/* vim: set filetype=mustache: */}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: {{ template "rebuildah-receiver.fullname" . }}
  labels: {{- include "rebuildah-receiver.labels" . | nindent 4 }}
spec:
  host: {{ .Values.domainname }}
  port:
    targetPort: 8080-8080
  to:
    kind: Service
    name: rebuildah-receiver
