{{/* vim: set filetype=mustache: */}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ template "rebuildah-receiver.fullname" . }}
  labels: {{- include "rebuildah-receiver.labels" . | nindent 4 }}
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: rebuildah-receiver
  type: ClusterIP
